abstract: A General Language Assistant as a Laboratory for Alignment - Given the broad capabilities of large language models, it should be possible to work towards a general-purpose, text-based assistant that is aligned with human values, meaning that it is helpful, honest, and harmless. As an initial foray in this direction we study simple baseline techniques and evaluations, such as prompting. We find that the benefits from modest interventions increase with model size, generalize to a variety of alignment evaluations, and do not compromise the performance of large models. Next we investigate scaling trends for several training objectives relevant to alignment, comparing imitation learning, binary discrimination, and ranked preference modeling. We find that ranked preference modeling performs much better than imitation learning, and often scales more favorably with model size. In contrast, binary discrimination typically performs and scales very similarly to imitation learning. Finally we study a `preference model pre-training' stage of training, with the goal of improving sample efficiency when finetuning on human preferences.
arxiv: https://arxiv.org/abs/2112.00861
construction:
  class: mcq
  n_choices: 2
few_shot: 0
language: eng
license: apache-2.0
system_prompt: null
task_name: hhh-alignment-harmless
timeline: ~2023.12.01
user_prompt_template:
  end_note: null
  example: null
  mid_note: null
  start_note: null
  test: "Question: \"{centerpiece}\" Answer: \n{options[0]}\n{options[1]} "
version: v1
web_source:
  file:
    dev: null
    test: data/*/task.json
  location: https://huggingface.co/datasets/HuggingFaceH4/hhh_alignment
