abstract: 'TruthfulQA: Measuring How Models Mimic Human Falsehoods - We propose a benchmark to measure whether a language model is truthful in generating answers to questions. The benchmark comprises 817 questions that span 38 categories, including health, law, finance and politics. We crafted questions that some humans would answer falsely due to a false belief or misconception. To perform well, models must avoid generating false answers learned from imitating human texts. We tested GPT-3, GPT-Neo/J, GPT-2 and a T5-based model. The best model was truthful on 58% of questions, while human performance was 94%. Models generated many false answers that mimic popular misconceptions and have the potential to deceive humans. The largest models were generally the least truthful. This contrasts with other NLP tasks, where performance improves with model size. However, this result is expected if false answers are learned from the training distribution. We suggest that scaling up models alone is less promising for improving truthfulness than fine-tuning using training objectives other than imitation of text from the web.'
arxiv: https://arxiv.org/abs/2109.07958
construction:
  class: mcq
  n_choices: mixed
few_shot: 0
language: eng
license: apache-2.0
system_prompt: null
task_name: truthfulqa-mc1
timeline: ~2022.05.08
user_prompt_template:
  end_note: null
  example: null
  mid_note: null
  start_note: null
  test: <wild*card>option_labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'; return f'{centerpiece} ' + ' '.join([f'{option_labels[i]}. {option}' for i, option in enumerate(options)])
version: v1
web_source:
  file:
    test: data/mc_task.jsonl
  location: https://github.com/sylinrl/TruthfulQA
