abstract: 'SocialIQA: Commonsense Reasoning about Social Interactions - We introduce Social IQa, the first largescale benchmark for commonsense reasoning about social situations. Social IQa contains 38,000 multiple choice questions for probing emotional and social intelligence in a variety of everyday situations (e.g., Q: "Jordan wanted to tell Tracy a secret, so Jordan leaned towards Tracy. Why did Jordan do this?" A: "Make sure no one else could hear"). Through crowdsourcing, we collect commonsense questions along with correct and incorrect answers about social interactions, using a new framework that mitigates stylistic artifacts in incorrect answers by asking workers to provide the right answer to a different but related question. Empirical results show that our benchmark is challenging for existing question-answering models based on pretrained language models, compared to human performance (>20% gap). Notably, we further establish Social IQa as a resource for transfer learning of commonsense knowledge, achieving state-of-the-art performance on multiple commonsense reasoning tasks (Winograd Schemas, COPA).'
arxiv: https://arxiv.org/abs/1904.09728
construction:
  class: mcq
  n_choices: 3
few_shot: 5
language: eng
license: cc-by-4.0
task_name: socialiqa
timeline: ~2019.04.22
user_prompt_template:
  example: 'Context: {context}\n\n Question: {centerpiece} A. {options[0]} B. {options[1]} C. {options[2]}? Answer: {correct_options[0]} \n\n'
  test: 'Context: {context}\n\n Question: {centerpiece} A. {options[0]} B. {options[1]} C. {options[2]}? Answer: '
version: v1
web_source:
  file:
    dev: socialIQa_v1.4/socialIQa_v1.4_dev.jsonl
    test: socialIQa_v1.4/socialIQa_v1.4_tst.jsonl
  location: https://maartensap.com/social-iqa/data/socialIQa_v1.4.tgz
