abstract: Can a Suit of Armor Conduct Electricity? A New Dataset for Open Book Question Answering - We present a new kind of question answering dataset, OpenBookQA, modeled after open book exams for assessing human understanding of a subject. The open book that comes with our questions is a set of 1329 elementary level science facts. Roughly 6000 questions probe an understanding of these facts and their application to novel situations. This requires combining an open book fact (e.g., metals conduct electricity) with broad common knowledge (e.g., a suit of armor is made of metal) obtained from other sources. While existing QA datasets over documents or knowledge bases, being generally self-contained, focus on linguistic understanding, OpenBookQA probes a deeper understanding of both the topic---in the context of common knowledge---and the language it is expressed in. Human performance on OpenBookQA is close to 92%, but many state-of-the-art pre-trained QA methods perform surprisingly poorly, worse than several simple neural baselines we develop. Our oracle experiments designed to circumvent the knowledge retrieval bottleneck demonstrate the value of both the open book and additional facts. We leave it as a challenge to solve the retrieval problem in this multi-hop setting and to close the large gap to human performance.
arxiv: https://arxiv.org/abs/1809.02789
construction:
  class: mcq
  n_choices: 4
few_shot: 5
language: eng
license: apache-2.0
task_name: openbookqa
timeline: ~2018.09.08
user_prompt_template:
  example: 'Question: {centerpiece} A. {options[0]} B. {options[1]} C. {options[2]} D. {options[3]}? Answer: {correct_options[0]} \n\n'
  test: 'Question: {centerpiece} A. {options[0]} B. {options[1]} C. {options[2]} D. {options[3]}? Answer: '
version: v1
web_source:
  file:
    dev: Data/Main/dev.jsonl
    test: Data/Main/test.jsonl
  location: https://ai2-public-datasets.s3.amazonaws.com/open-book-qa/OpenBookQA-V1-Sep2018.zip
