abstract: 'Program Induction by Rationale Generation: Learning to Solve and Explain Algebraic Word Problems - Solving algebraic word problems requires executing a series of arithmetic operations—a program—to obtain a final answer. However, since programs can be arbitrarily complicated, inducing them directly from question-answer pairs is a formidable challenge. To make this task more feasible, we solve these problems by generating answer rationales, sequences of natural language and human-readable mathematical expressions that derive the final answer through a series of small steps. Although rationales do not explicitly specify programs, they provide a scaffolding for their structure via intermediate milestones. To evaluate our approach, we have created a new 100,000-sample dataset of questions, answers and rationales. Experimental results show that indirect supervision of program learning via answer rationales is a promising strategy for inducing arithmetic programs.'
arxiv: https://arxiv.org/abs/1705.04146
construction:
  class: mcq
  n_choices: 5
few_shot: 5
language: eng
license: apache-2.0
task_name: aqua-rat
timeline: ~2017.10.23
user_prompt_template:
  example: "Question: {centerpiece} A. {options[0]} B. {options[1]} C. {options[2]} D. {options[3]} E. {options[4]}? Answer: {correct_options[0]} \n\n"
  test: 'Question: {centerpiece} A. {options[0]} B. {options[1]} C. {options[2]} D. {options[3]} E. {options[4]}? Answer: '
version: v1
web_source:
  file:
    dev: dev.json
    test: test.json
  location: https://github.com/google-deepmind/AQuA
